name: mpg-data-warehouse
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - db-dtypes
  - pyyaml
  - fsspec
  - gcsfs
  - jupyter
  - r-base
  - r-irkernel
  - r-tidyverse
  - r-knitr
  - r-bigrquery
  - pip
  - pip:
    - google-auth>=2.14.1
    - google-api-core>=2.11.1
    - google-cloud-core>=2.0.0
    - google-cloud-bigquery>=3.0.0
    - google-cloud-storage>=3.0.0